### PR TITLE
Merging ECash SLPDB into Electron-Cash-SLP 

### PR DESCRIPTION
**Pull request by jusufgit1503**

### CODE REVIEW

**Comment by jusufgit1503** [comment]
TX validation methods commit contains changes for a bug where SLPDB could not be disabled with its checkbox, but only with enabling GS. Now, both methods can be enabled and disabled individually.

**Comment by cculianu** [comment]
I'm out of the loop here -- is this project getting rebranded? Are we sure "ECash" is a good name?? (Isn't there an eCash crypto coin?).

**Comment by blockparty-sh** [comment]
> I'm out of the loop here -- is this project getting rebranded? Are we sure "ECash" is a good name?? (Isn't there an eCash crypto coin?).

Hi! Project isn't being rebranded. This is merge of actorforths branch which was called ecash-slpdb to differentiate it from electron cash slp, it was named prior to taxcoin's rebranding efforts.

**Comment by darnellbelcourt99999** [comment]
No money no service

**Comment by OPReturnCode** [comment]
It seems fine. Merging it.

**Pull request merged**
