### PR TITLE
 Switched wine/windows building to use docker exclusively

### PR DESCRIPTION
**Pull request by cculianu**
- contrib/build-wine/build.sh is the entry point (requires docker).
Works on Linux and MacOS host.

- Windows hosts will need to do things manually adapting the
instructions in contrib/build-wine/docker/README.md

- Added a linux 'build' script for releasing our funky source tarball
with secp embedded called contrib/make_linux_sdist

- electrum-locale is now a submodule  which lives inside contrib/ and
points to the same repo as before.  This makes things a lot easier and
is cleaner for scripting.

- Updated all relevant READMEs

### CODE REVIEW

**Comment by cculianu** [comment]
Note this works 100%. Try it out too -- instructions are in `contrib/build-wine` -- it's basically::

    $ contrib/build-wine/build.sh master

**Comment by cculianu** [comment]
Nice catch on the typo! Thanks!

**Comment by jcramer** [comment]
@cculianu, made a final tweak to README and it builds. Also tested the installer out on Windows machine, it all works great.

**Comment by cculianu** [comment]
Awesome man. Already merged on EC too.  I'm really happy we're going this route!

**Comment by jcramer** [comment]
@cculianu Did you notice the updates I made in commit 5dc178f ? Should this be corrected in mainline?

**Pull request merged**
